### ISSUE TITLE
Manage updates via CI

### ISSUE THREAD

**Issue by ellismg** [pulumi/get.pulumi.com#4]
Today changes to the infrastructure must be run on a developer machine and updating the install.sh script in our bucket requires manual invocations of `aws s3 cp`.  We should fix both of these issues, with a `production` branch that does updates when needed.

**Comment by joeduffy** [comment]
Let's do this, rather than pushing again. Part of the motivation for doing this as an open source Pulumi program was to demonstrate "best practices" for real-world Pulumi programs, and CI/CD is a key part of best practices, and will serve as a nice reference to our community who may want to do the same.

**Comment by ellismg** [comment]
This is now complete with 60d76e30ff2401dd0f73ab34c849e3cd01703a2d
